### ISSUE TITLE
Base path for API URIs missing

### ISSUE THREAD

**Issue by jmcanterafonseca** [sensinov/djane#12]
You say

>To test that you have correctly installed the server, you can run your first query
> curl "http://localhost:3000/subscriptions" -H 'Accept: application/ld+json'
> 

Be careful the base path for all API URIs is `ngsi-ld/v1/` so 

it should be `http://localhost:3000/ngsi-ld/v1/subscriptions`

**Comment by gghabri** [comment]
Thanks for your feedback. I will commit the changes during the day.
