### ISSUE TITLE
 HTTP Location header missing

### ISSUE THREAD

**Issue by jmcanterafonseca** [sensinov/djane#13]
The HTTP Location header should be properly set ....

**Comment by mbenalaya** [comment]
Hi Jose
Nice catch! We will submit a patch asap.
Thanks again for your valuable feedback.

**Comment by gghabri** [comment]
Thank @jmcanterafonseca for your feedback. Location header is now supported. Commit :
https://github.com/sensinov/djane/commit/a11ae4bcc71e5a96c13289372015087400741d3b
