### ISSUE TITLE
Accept can be empty or "*/*"

### ISSUE THREAD

**Issue by jmcanterafonseca** [sensinov/djane#14]
Spec says:

Accept header shall be "application/json", "application/ld+json" or "*/*". A non-present accept header is also allowed. In that particular case "application/json" shall be assumed. 

Unfortunately the spec does not say anything when accept is "*/* what kind of content should be sent in the response. Probably in that case the the safest is 'application/json' 

/cc @kzangeli , so that Orion-LD can exhibit the same behaviour

**Comment by gghabri** [comment]
Thanks @jmcanterafonseca for your comment. Accept header management is now updated. Commit : https://github.com/sensinov/djane/commit/2e91bb310d830a5a740ac3073f836211ac8eb29e
