### ISSUE TITLE
Individual Entity Retrieval shall return a JSON object and not a JSON Array

### ISSUE THREAD

**Issue by jmcanterafonseca** [sensinov/djane#17]
See 

https://fiware-datamodels.readthedocs.io/en/latest/ngsi-ld_howto/index.html#api-examples

**Comment by gghabri** [comment]
It is now handled (commit: https://github.com/sensinov/djane/commit/ae49bf40b1b350e28dae6636ae97df2b0553f9d1) . thanks for the comment.
