### ISSUE TITLE
MongoDB connection string

### ISSUE THREAD

**Issue by Glagnar** [sensinov/djane#24]
I have a connection string like this:
```
mongodb+srv://user:AQBWyjHRMk5G9r3h@gilbert-kbvrc.mongodb.net/test?retryWrites=true&w=majority
```
Will this be supported ?
Perhaps using a whole connection string as input, and removing all the 'dbHost', 'dbPort' etc. ? For my purposes I have modified the config file and modified the line below...
```
const mongoDBHost = process.env.DB_CONNECTION_STRING || dbServer + dbHost + ':' + dbPort + '/' + DataBaseName;
```

**Comment by gghabri** [comment]
Thanks @Glagnar , I am working on it :-)

**Comment by gghabri** [comment]
please check commit https://github.com/sensinov/djane/commit/5129e38de52b8c9772f328f2337c26fab33ba8fe
Djane supports now a a whole connection string.
