### ISSUE TITLE
Example is wrong either the type parameter or the attrs must be present

### ISSUE THREAD

**Issue by jmcanterafonseca** [sensinov/djane#26]
https://github.com/sensinov/djane/blob/master/tutorials/REST%20API.md#retrieve-entities

You always need to provide either the `type` parameter or the `attrs` parameter.

**Comment by gghabri** [comment]
Hi, Thanks for feedback. This issue is processed in commit 
https://github.com/sensinov/djane/commit/bd0260f9cf79400b97a02ecab5fcda692ffb69d3
