### ISSUE TITLE
djane_mongo_1 exited with code 14

### ISSUE THREAD

**Issue by ciesse79** [sensinov/djane#27]
Hi all,
I'm trying to set up djane for testing purpose using docker compose.
Cloned all the repository and executed docker-compose up but it crashes with:

mongo_1  | 2019-07-31T17:42:20.417+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1564594940:417839][1:0x7f11f1cbfa80], connection: __posix_open_file, 715: /dat
a/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1564594940:417839][1:0x7f11f1cbfa80], connection: __posix_open_file, 715: /data/db/WiredTiger.wt:
handle-open: open: Operation not permitted
mongo_1  | 2019-07-31T17:42:20.419+0000 W STORAGE  [initandlisten] Failed to start up WiredTiger under any compatibility version.
mongo_1  | 2019-07-31T17:42:20.419+0000 F STORAGE  [initandlisten] Reason: 1: Operation not permitted
mongo_1  | 2019-07-31T17:42:20.419+0000 F -        [initandlisten] Fatal Assertion 28595 at src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 704
mongo_1  | 2019-07-31T17:42:20.419+0000 F -        [initandlisten]
mongo_1  |
mongo_1  | ***aborting after fassert() failure
mongo_1  |
mongo_1  |
djane_mongo_1 exited with code 14
djane_1  | wait-for-it.sh: timeout occurred after waiting 30 seconds for mongo:27017
djane_1  |
djane_1  | > djaneio@1.0.0 migrate /usr/src/app
djane_1  | > node migrate.js
djane_1  |
djane_1  | Trying to connect to DB mongodb://mongo:27017/ngsi_ld_bd
djane_1  | Error: getaddrinfo ENOTFOUND mongo
djane_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
djane_1  |   errno: 'ENOTFOUND',
djane_1  |   code: 'ENOTFOUND',
djane_1  |   syscall: 'getaddrinfo',
djane_1  |   hostname: 'mongo'
djane_1  | }
djane_1  | /usr/src/app/node_modules/mongodb/lib/topologies/server.js:240
djane_1  |             throw err;
djane_1  |             ^
djane_1  |
djane_1  | TypeError: Cannot read property 'collection' of undefined
djane_1  |     at createUser (/usr/src/app/migrate.js:287:6)
djane_1  |     at /usr/src/app/migrate.js:299:5
djane_1  |     at /usr/src/app/lib/mongo.js:46:9
djane_1  |     at /usr/src/app/lib/mongo.js:30:24
djane_1  |     at /usr/src/app/node_modules/mongodb/lib/utils.js:411:14
djane_1  |     at executeCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:401:25)
djane_1  |     at /usr/src/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:285:21
djane_1  |     at connectCallback (/usr/src/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:265:5)
djane_1  |     at /usr/src/app/node_modules/mongodb/lib/operations/mongo_client_ops.js:353:14
djane_1  |     at Server.<anonymous> (/usr/src/app/node_modules/mongodb/lib/topologies/server.js:237:11)
djane_1  | npm ERR! code ELIFECYCLE
djane_1  | npm ERR! errno 1
djane_1  | npm ERR! djaneio@1.0.0 migrate: `node migrate.js`
djane_1  | npm ERR! Exit status 1
djane_1  | npm ERR!
djane_1  | npm ERR! Failed at the djaneio@1.0.0 migrate script.
djane_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
djane_1  |
djane_1  | npm ERR! A complete log of this run can be found in:
djane_1  | npm ERR!     /root/.npm/_logs/2019-07-31T17_43_40_210Z-debug.log
djane_djane_1 exited with code 1

What is wrong?

**Comment by gghabri** [comment]
Hi, 
This problem is not related to djane source code. It seems that you have permission problem related to mongodb. This could happen if you are running mongodb on windows virtual machine.
