### ISSUE TITLE
Should return 404 on entity not found

### ISSUE THREAD

**Issue by mainakae** [sensinov/djane#31]
[Line 83 of routes/entities.js](https://github.com/sensinov/djane/blob/aae5e361d1de65e05e5a696d30aa1c5afbc41b0c/routes/entities.js#L83-L91) doesn't account for returning 404 message when no entity has been found for the given query. This doesn't comply with ETSI-CIM NGSI-LD standard and causes compatibility issues.

code referred:

```javascript
router.get('/entities/:entityId', auth.checkToken, function(req, res) {
    db.collection('entities').findOne({'id': req.params.entityId}, {projection:{_id: 0}}, function (err, result) {
        if (err) {
            return console.log(err);
        } else {
            res.status(200);
            res.json(result);
        }}); 
});
```

**Comment by gghabri** [comment]
Thanks for your feedback. This handled in commit https://github.com/sensinov/djane/commit/a0bfa5fdbf7ea112fdd2bdb48bcec53ac4fbe069
